# Generated by Django 3.2.7 on 2021-10-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_literal_predicate_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='statements',
            field=models.ManyToManyField(to='notes.Statement'),
        ),
    ]
