# Generated by Django 3.2.7 on 2021-10-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_statements'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='source',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
