# Generated by Django 3.2.7 on 2021-10-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(unique=True)),
                ('content_raw', models.TextField(blank=True)),
                ('content_plain', models.TextField(blank=True)),
            ],
        ),
    ]
