# Generated by Django 3.2.7 on 2021-10-19 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
