# Generated by Django 3.2.7 on 2021-10-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
                ('format', models.CharField(choices=[(0, 'MP3')], max_length=10)),
                ('file', models.FileField(upload_to='')),
            ],
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
        ),
    ]
