# Generated by Django 3.2.7 on 2021-10-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_annotation_audiodocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='end',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotation',
            name='start',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotation',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
