# Generated by Django 3.2.7 on 2021-10-21 14:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20211021_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='audiodocument',
            name='file',
            field=models.FileField(upload_to='documents/audio', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
        migrations.AlterField(
            model_name='audiodocument',
            name='format',
            field=models.CharField(choices=[('MP3', 'mp3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='uri',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
